server:
  port: 8080
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://<HOST>:<PORT>//log_collector?allowPublicKeyRetrieval=true&useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password:
  jpa:
    show-sql: true
    hibernate:
      #use-new-id-generator-mappings: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: <MAIL ADDRESS>
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  jackson:
    deserialization:
      # 클라이언트에서 서버로 알 수 없는 데이터 필드를 전달할 경우 HttpMessageNotReadableException 를 발생시키는 설정
      fail-on-unknown-properties: true

  rabbitmq:
    host: <HOST>
    port: 5672
    username: guest
    password:
